os:
  editPreset: "nvim"

keybinding:
  universal:
    return: "<c-/>"

gui:
  scrollHeight: 10
  scrollPastBottom: false
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline

git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
